### ISSUE TITLE
Teensy 3.2

### ISSUE THREAD

**Issue by Sthopeless** [thedalles77/USB_Laptop_Keyboard_Controller#1]
Hello!

First of all let me thank you for this incredible work, I have been looking for something similar forever!
I very often have old or broken laptops to recycle what I can reuse so I have a couple of keyboards and mouses for testing.

I have also found this plug adapter on Aliexpress https://www.aliexpress.com/item/FPC-FFC-Cable-6-8-10-12-14-20-30-40-50-PIN-1-0-mm/32885789207.html?spm=a2g0s.13010208.99999999.9.278d3c004mSTEI that might be handy without the pre-made PCB or for testing purposes :smile: 

The Teensy 3.2 board, I see it's a lot more expensive then Arduino MEGA or Arduino DUE clones for example that have all the necessary Digital Pins, is it possible to replace the Teensy with one of this board (they are alot cheaper and I already have them on hand) and still use your code?

**Comment by thedalles77** [comment]
Hi Sthopeless, thanks for the kind words. I'm never sure if anyone looks at my repo. The Aliexpress plug adapter would be an inexpensive way to hook up the FPC cable and not have to solder the fine pitch connector. I must admit I've never used anything but Teensy microcontrollers so I don't know if the Arduino Mega or DUE would work with my code. When I first started working with Teensy's as keyboard and touchpad controllers, they seemed to have the support of the mechanical keyboard folks so I never tried anything else. A quick Google search came up with some issues regarding USB discussed in the [PJRC Forum.](https://forum.pjrc.com/threads/52337-Possible-to-run-Teensyduino-code-directly-on-Arduino-MEGA) 
You could try compiling my code on your Arduino and see what errors you get.  If you can't figure out what the errors are for, send your results into the PJRC forum. They seem to be good at answering those kinds of questions.
Sorry I'm not much help. 
Frank

**Comment by thedalles77** [comment]
Closed
