### ISSUE TITLE
Debounce, prevent key repeat

### ISSUE THREAD

**Issue by Raduq91** [thedalles77/USB_Laptop_Keyboard_Controller#10]
Hi, can you add a debounce of sort, to not repeat the same key.
Sometimes, when I press for example X it double presses

(I used :https://github.com/thedalles77/USB_Laptop_Keyboard_Controller/tree/master/Example_Keyboards/Dell_Latitude_D630 for my keyboard, usb membrane keyboard, with teensy 4.1)

(I lowered the delays :
for (int x = 0; x < rows_max; x++) {   // loop thru the rows
    go_0(Row_IO[x]); // Activate Row (send it low) 
    delayMicroseconds(15) )

If you can add something to discard key repeat, without adding delay.Discard key repeat in a span of 1ms.
(in a game I have X binded to open a menu, it opens at key press and closes at key press, when I press X, sometimes it shows the menu and I release the button and it closes the menu)

**Comment by thedalles77** [comment]
Hello, this is the first time I've heard of my code giving a double press so I'll need some more information. Does the double press happen when you are using the keyboard in a regular "typing" fashion in a text file? Is it only doing it with the X key? Have you tried compiling the Teensy 4.1 with a reduced clock speed? What speed is the overall loop rate (the delay at the end of the code)? Normally it's in the 20 to 30 msec range which takes care of debouncing. Please send me your latest version of Teensy code along with a list of things you've already tried to thedalles77@gmail.com            I'll look it over and see if I can add a debouncer
