### ISSUE TITLE
ESP32 requires different I2C sequence

### ISSUE THREAD

**Issue by gearsincorg** [thedalles77/USB_Laptop_Keyboard_Controller#12]
Regarding:  
[USB_Laptop_Keyboard_Controller](https://github.com/thedalles77/USB_Laptop_Keyboard_Controller)/[Example_Touchpads](https://github.com/thedalles77/USB_Laptop_Keyboard_Controller/tree/master/Example_Touchpads)/Azoteq_TP.ino

I'm using this code on an ESP32 Arduino project, and the I2C sequence shown is giving bad results.

The issue seems to be the second endTransmission() call.
Your code calls this after requesting Wire.requestFrom(), but before actually retreiving the read bytes..

```
Wire.requestFrom(tp_address,16); // read 16 bytes starting at 0x000d
    if (Wire.endTransmission(true) == 0) {  // send stop bit and check if TP "acked"
```

However, I have discovered that issuing this call appears to clear/corrupt the receive character buffer.

To get this code to work with the ESP32 I needed to move the second endTransmission() call to AFTER thee Wire.read()'s calls, or eliminate it alltogether.  Since the requestFrom() call returns the number of characters read, it does not require an additional endTransmission() call to actually fetch the characters.

**Comment by thedalles77** [comment]
I tried doing what you said with a Teensy 3.2 and it caused the Azoteq touchpad to not respond at all. Perhaps it's a difference in how the Teensy does I2C versus the ESP32. If you have your ESP32 code posted somewhere, send me a link so I can give the link in my Github Readme and on my Hackster.IO site so other ESP32 users can find your code.
