### ISSUE TITLE
Circuit board for 30 pins 1mm pitch to Teensy 4.0

### ISSUE THREAD

**Issue by Bergum** [thedalles77/USB_Laptop_Keyboard_Controller#14]
As a noob in this field.
How can i change your file to accept a FPC 30 pin 1mm pitch for a Teensy 4.0?
What file am i to start with?

I am in the process of converting a HP ProBook 6545b with a keybooard with full numeric on the side, to a Keyboard/screen/trackpad for my phone. Love the work you have done.

**Comment by thedalles77** [comment]
You don't need to change any files, just use the existing Teensy 4.0 connector board "Keyboard_Scanner_4p0" and solder the FPC connector on pads 1 thru 30, leaving pads 31 thru 34 blank.

**Comment by Bergum** [comment]
Thank you for you kind guiding.
The PCB are now in the making.
