### ISSUE TITLE
Keyboard X61 with huawei board

### ISSUE THREAD

**Issue by isulpt** [thedalles77/USB_Laptop_Keyboard_Controller#15]
Hello,
I'm trying to install a X61 keyboard with a huawei motherboard with ryzen CPU. Your project works with this mods? or i need to change something on x61 files? because my keyboard don't works with the mods. 
Thank you

**Comment by thedalles77** [comment]
I uploaded Lenovo_T61_Keyboard code for the Teensy 3.2 and LC that does not include the trackpoint so you won't need to make your own for debug.

**Comment by isulpt** [comment]
Great. Thank you. Will try with this new update. Thank you so much
