### ISSUE TITLE
Optical drive, HDD, SD card reader, USB etc

### ISSUE THREAD

**Issue by JohnVeness** [thedalles77/USB_Laptop_Keyboard_Controller#16]
Hi, this isn't an "issue" as such, just a thanks for this project. I was thinking about doing the exact same thing and searched first to see if someone else already had, and came across your instructable.

I was thinking - it would be great to be able to use some more of the components inside the laptop, presenting them as USB devices to the managed server or internal KVM. For example, (if present) internal optical drive or floppy drive, internal HDD or SSD, card reader, and any "spare" USB sockets for use with flash drives. Maybe even audio sockets, built-in speakers, webcams, Wi-Fi cards, HDMI input etc.!

I realise that it's getting to the point that I'm almost recreating an entire computer, but having all these devices in one handy portable package, that could be made available to external USB hosts, would be very useful for many projects, e.g. testing a bulk load of desktop/tower PCs, testing certain types of games consoles, maybe even plugging into mobile phones, etc.

Thanks again.

**Comment by thedalles77** [comment]
I'm glad you found my Instructable useful and appreciate your thanks. Your idea of making all the devices accessible over USB would be a fun project with lots of things to learn (at least for me). 
Cheers
