### ISSUE TITLE
Special key formatting.

### ISSUE THREAD

**Issue by mikekscholz** [thedalles77/USB_Laptop_Keyboard_Controller#5]
I ran into a bit of a conundrum with my custom keyboard conversion, being that its a thumb-board and therefore has some non-standard layout, and I found that I was able to directly input the ASCII characters into the keymatrix on the Fn layer, and it just works. **No other modifications needed!** Naturally I was blown away at how well it worked on the **very first upload** to a brand new teensy3.2.

![RII518](https://user-images.githubusercontent.com/42889385/77985984-ec8c9400-72e3-11ea-8cca-1f9bbb5a758c.jpg)

Here is my matrix layout as an example for anyone else that may find this useful. Go into your C:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy3 and open keylayouts.h scrolling down to line #230 begins the list of ASCII characters that should work like this. Just surround the characters with single quotes in your matrix `{'<','>'}`

```
int normal[rows_max][cols_max] = {
  {0,0,0,0,KEY_MEDIA_MUTE,KEY_MEDIA_VOLUME_DEC,KEY_MEDIA_VOLUME_INC,KEY_MEDIA_PREV_TRACK,KEY_MEDIA_PLAY_PAUSE,KEY_MEDIA_NEXT_TRACK,0,KEY_BACKSPACE},
  {KEY_ESC,KEY_1,KEY_2,KEY_3,KEY_4,KEY_5,KEY_6,KEY_7,KEY_8,KEY_9,KEY_0,KEY_TILDE},
  {KEY_TAB,KEY_Q,KEY_W,KEY_E,KEY_R,KEY_T,KEY_Y,KEY_U,KEY_I,KEY_O,KEY_P,KEY_BACKSLASH},
  {KEY_CAPS_LOCK,KEY_A,KEY_S,KEY_D,KEY_F,KEY_G,KEY_H,KEY_J,KEY_K,KEY_L,KEY_SEMICOLON,KEY_QUOTE},
  {0,KEY_Z,KEY_X,KEY_C,KEY_V,KEY_B,KEY_N,KEY_M,KEY_SLASH,KEY_UP,0,KEY_ENTER},
  {0,0,0,0,KEY_MINUS,KEY_EQUAL,0,KEY_SPACE,0,KEY_DOWN,KEY_LEFT,KEY_RIGHT}
};

// Load the modifier key matrix with key names at the correct row-column location. 
// A zero indicates no modifier key at that location.
int modifier[rows_max][cols_max] = {
  {0,0,0,MODIFIERKEY_GUI,0,0,0,0,0,0,0,0},
  {0,0,0,0,0,0,0,0,0,0,0,0},
  {0,0,0,0,0,0,0,0,0,0,0,0},
  {0,0,0,0,0,0,0,0,0,0,0,0},
  {MODIFIERKEY_SHIFT,0,0,0,0,0,0,0,0,0,0,0},
  {MODIFIERKEY_FN,0,MODIFIERKEY_CTRL,MODIFIERKEY_ALT,0,0,0,0,0,0,0,0}
};

// Load the media key matrix with Fn key names at the correct row-column location. 
// A zero indicates no media key at that location.
int media[rows_max][cols_max] = {
    {0,0,KEY_F1,KEY_F2,KEY_F3,KEY_F4,KEY_F5,KEY_F6,KEY_F7,KEY_F8,0,KEY_DELETE},
    {0,0,0,0,0,0,0,0,KEY_F9,KEY_F10,KEY_F11,KEY_F12},
    {0,0,0,0,0,0,0,0,0,0,'[',']'},
    {0,0,0,0,0,0,0,0,'<','>','{','}'},
    {0,0,0,0,0,0,0,KEY_COMMA,KEY_PERIOD,KEY_PAGE_UP,0,0},
    {0,0,0,0,0,0,0,0,0,KEY_PAGE_DOWN,KEY_HOME,KEY_END}
};
```

**Comment by thedalles77** [comment]
Mike, that's a cool little keyboard you got working. I didn't know you could send the ASCII characters like that. Kudos for figuring it out on the first try (that never happens for me). Please send in a picture of your keyboard to the "I made it" link at the end of my Instructable along with a description of your ASCII character mod and a part number for the keyboard or the computer it come from. This will be useful for others with non-standard keyboards. If you want me to post your complete code in a folder here at my repo, send it to me by email at thedalles77@gmail.com or attach the files to this issue.
Thanks
Frank
