### ISSUE TITLE
Cleaning up matrixgenerator output

### ISSUE THREAD

**Issue by gi1mic** [thedalles77/USB_Laptop_Keyboard_Controller#6]
Linux users (or windows users using the Ubuntu shell) can cleanup the output of matrixgenerator.py by piping the output through the trim command to remove the single quotes i.e.

    python matrixgenerator_LC.py  | tr -d \'

**Comment by thedalles77** [comment]
Thank you gi1mic for this work-around. Another user named apiraino has modified the python programs to eliminate the single quotes.
